export const TESTIMONIALS = [
    {
      name: "Deltagarage.",
      role: "Founder",
      company: "Delta Garage",
      companyUrl: "https://deltagarage.in",
      image: "https://ui-avatars.com/api/?name=Deltagarage.&background=0f172a&color=ffffff&bold=true",
      content: "Loved the website design! Clean, fast, and exactly what I needed for my garage business.",
      time: "12:30 PM",
      date: "Jul 2, 2024",
    },
    {
      name: "Brandcorner.",
      role: "Owner",
      company: "Brand Corner",
      companyUrl: "https://brandcorner.co.in",
      image: "https://ui-avatars.com/api/?name=Brandcorner.&background=0f172a&color=ffffff&bold=true",
      content: "Shopigo gave me a premium website without any tech headache. Highly recommend for Instagram sellers!",
      time: "4:00 PM",
      date: "Jul 5, 2024",
    },
    {
      name: "Stylezone.",
      role: "Co-Founder",
      company: "The Style Zone",
      companyUrl: "https://thestylezone.in",
      image: "https://ui-avatars.com/api/?name=Stylezone.&background=0f172a&color=ffffff&bold=true",
      content: "Our fashion store finally looks like a brand! Easy to manage and customers love it.",
      time: "11:15 AM",
      date: "Jun 28, 2024",
    },
    {
      name: "Motostore.",
      role: "Owner",
      company: "Moto Store",
      companyUrl: "https://motostore.co.in",
      image: "https://ui-avatars.com/api/?name=Motostore.&background=0f172a&color=ffffff&bold=true",
      content: "From start to launch, everything was smooth. Site looks pro and works great!",
      time: "3:20 PM",
      date: "Jul 7, 2024",
    },
    {
      name: "Footmart.",
      role: "Founder",
      company: "Footmart",
      companyUrl: "https://footmart.co.in",
      image: "https://ui-avatars.com/api/?name=Footmart.&background=0f172a&color=ffffff&bold=true",
      content: "Great support and the site is super fast. My sales improved after switching to Shopigo.",
      time: "10:45 AM",
      date: "Jul 10, 2024",
    },
  ];
  